services:
  docs-development:
    build:
      context: ../../
      dockerfile: docker/development/docs.dockerfile
      secrets:
        - turbo_token
    environment:
      TURBO_TEAM: ${TURBO_TEAM}
    image: docs-development:latest
    ports:
      - "3001:3000"

secrets:
  turbo_token:
    environment: TURBO_TOKEN