name: my-turborepo-development
services:
  web-development:
    build:
      context: ../../
      dockerfile: docker/development/web.dockerfile
      secrets:
        - turbo_token
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        TURBO_TEAM: ${TURBO_TEAM}
    environment:
      - HOSTNAME="0.0.0.0"
      - PORT=${PORT}
    image: web-development:latest
    ports:
      - "${PORT}:${PORT}"

secrets:
  turbo_token:
    environment: TURBO_TOKEN