name: CI

on: [push, pull_request]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

# This ensures that any new push cancels an older workflow if it's running on the same branch.
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # JOB to run change detection
  detect-changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      web: ${{ steps.filter.outputs.web }}
      ui-package: ${{ steps.filter.outputs.ui-package }}
    steps:
      # For pull requests it's not necessary to check out the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs: apps/docs/**
            web: apps/web/**
            ui-package: packages/ui/**
  
  lint:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [detect-changes, lint]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test all apps
        if: ${{ needs.detect-changes.outputs.ui-package == 'true' }}
        run: pnpm test

      - name: Test docs
        if: ${{ needs.detect-changes.outputs.ui-package != 'true' && needs.detect-changes.outputs.docs == 'true' }}
        run: pnpm test -F docs

      - name: Test web
        if: ${{ needs.detect-changes.outputs.ui-package != 'true' && needs.detect-changes.outputs.web == 'true' }}
        run: pnpm test -F web